"""
run_statistical_tests.py

This script performs paired t-tests comparing evaluation performance of different model runs
(specifically, RSR regularisation versus vanilla continued language modeling) across subjects.

Workflow Context:
- Orchestrated at the end of the evaluation phase (e.g. by run_all.ps1 or run_eval_downstream.ps1) 
  after fMRI results have been extracted and processed.
- Imports: Loads output JSON files generated by eval_pereira_rsa.py and eval_pereira_voxel_encoding.py.
- Computes statistical significance (p-values and t-statistics) comparing RSR and vanilla models.
- Outputs: Prints statistical reports directly to stdout for verification.
"""
import json
import os
import numpy as np
from scipy.stats import ttest_rel

def load_json(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

def run_ttest(name_a, name_b, array_a, array_b):
    if len(array_a) < 2:
        return None
    t_stat, p_val = ttest_rel(array_a, array_b)
    mean_diff = np.mean(array_a) - np.mean(array_b)
    return t_stat, p_val, mean_diff

def main():
    results_dir = "results_downstream_bdhomepc_2026-07-05"
    import glob
    encoding_paths = glob.glob(os.path.join(results_dir, "pereira_encoding_results*.json"))
    encoding_path = encoding_paths[0] if encoding_paths else ""
    
    rsa_paths = glob.glob(os.path.join(results_dir, "pereira_rsa_results*.json"))
    rsa_path = rsa_paths[0] if rsa_paths else ""
    
    acc_paths = glob.glob(os.path.join(results_dir, "pereira_2v2_results*.json"))
    acc_path = acc_paths[0] if acc_paths else ""
    
    print("=== Multi-Subject Paired t-tests (rsr_all vs vanilla_all) ===\n")
    
    if os.path.exists(encoding_path):
        encoding_data = load_json(encoding_path)
        print("--- Voxelwise Encoding (Layer 11) ---")
        layer = '11'
        rsr_scores = encoding_data['rsr_all'][layer]
        vanilla_scores = encoding_data['vanilla_all'][layer]
        print(f"N subjects = {len(rsr_scores)}")
        t_stat, p_val, mean_diff = run_ttest('rsr_all', 'vanilla_all', rsr_scores, vanilla_scores)
        print(f"Mean Difference: {mean_diff:+.4f}")
        print(f"Paired t-test: t = {t_stat:.4f}, p = {p_val:.4f}\n")
        
    if os.path.exists(rsa_path):
        rsa_data = load_json(rsa_path)
        print("--- RSA: All pairs (Layer 5) [wiki_avg] ---")
        layer = '5'
        rsr_scores = rsa_data['wiki_avg']['rsr_all']['All pairs'][layer]
        vanilla_scores = rsa_data['wiki_avg']['vanilla_all']['All pairs'][layer]
        print(f"N subjects = {len(rsr_scores)}")
        t_stat, p_val, mean_diff = run_ttest('rsr_all', 'vanilla_all', rsr_scores, vanilla_scores)
        print(f"Mean Difference: {mean_diff:+.4f}")
        print(f"Paired t-test: t = {t_stat:.4f}, p = {p_val:.4f}\n")
        
    if os.path.exists(acc_path):
        acc_data = load_json(acc_path)
        print("--- 2vs2 Accuracy (Layer 5) [wiki_avg] ---")
        layer = '5'
        rsr_scores = acc_data['wiki_avg']['rsr_all'][layer]
        vanilla_scores = acc_data['wiki_avg']['vanilla_all'][layer]
        print(f"N subjects = {len(rsr_scores)}")
        t_stat, p_val, mean_diff = run_ttest('rsr_all', 'vanilla_all', rsr_scores, vanilla_scores)
        print(f"Mean Difference: {mean_diff:+.4f}")
        print(f"Paired t-test: t = {t_stat:.4f}, p = {p_val:.4f}\n")

if __name__ == "__main__":
    main()
